### PR TITLE
Pin RefinedRust to a specific version

### PR DESCRIPTION
**Pull request by lgaeher**
## Description of the changes
Currently, we do not fix a particular RefinedRust version. Since RefinedRust has regular breaking changes, fixing a particular version and only updating it together with new verification results/when the need arises will reduce the maintenance burden.

For this, I included RefinedRust as a submodule, as this is how we pin existing dependencies as well.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Formal verification
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactorization (non-breaking change which improves code quality)

## How to test this PR?
It's sufficient to check whether CI passes.

### CODE REVIEW

**Comment by wojciechozga** [comment]
Thank you for the PR. I am fine with pinning RefinedRust. However, t current `build` pipeline fails and we have to fix it first. The error indicates lack of disk space during the build. Probably, CI initializes all git submodules, including newly added RefinedRust, and then reaches max space size when it tries to build the test VM image. Reconfiguring the build configuration, so that it does not initialize the RefinedRust git module when building the security monitor should fix the issue.

**Comment by lgaeher** [comment]
Yeah, that makes sense. I'm not sure the changes in this PR are the root cause for the failure though. After this run failed, I re-ran the build pipeline on current main, and it fails with the same message: https://github.com/IBM/ACE-RISCV/actions/runs/10014257449/job/28567659391

I'm not sure what may have caused this, since the same job ran fine a couple of weeks ago.

**Comment by wojciechozga** [comment]
Right, probably Github actions reduces disk space for the pipeline jobs. We can then decrease the test VM image size. Let me try it out.

**Comment by lgaeher** [comment]
Seems like this is a problem others are experiencing as well: https://github.com/actions/runner-images/issues/10386

Some people report that switching to ubuntu-24.04 works. Or we could wait until this is fixed.

**Comment by wojciechozga** [comment]
I have changed CI base image to Ubuntu-24.04 and, indeed, it works fine. Looks like we can merge this PR now.

**Comment by lgaeher** [comment]
Thanks!

**Pull request merged**
